export const ActionTypes = {
    SET_PRODUCTS : 'SET_PRODUCTS',
    SELECTED_PRODUCT : 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT : 'REMOVE_SELECTED_PRODUCT',
    SET__LIMITPRODUCT :"SET__LIMITPRODUCT",
    SET_PRODUCT_CATEGORIES:"SET_PRODUCT_CATEGORIES",
    SET_SELECTED_CATEGORIES: " SET_SELECTED_CATEGORIES",
    INCREMENT_COUNT :'INCREMENT_COUNT',
    DECREMENT_COUNT:'DECREMENT_COUNT',
    ADD_PRODUCT: "ADD_PRODUCT",
    REMOVE_PRODUCT: "REMOVE_PRODUCT",
    ADD_TO_CART : 'ADD_TO_CART'
};
